# Generated by Django 6.0.7 on 2026-07-29 10:29

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('full_name_fa', models.CharField(max_length=250, null=True)),
                ('full_name_en', models.CharField(max_length=250, null=True)),
                ('full_name_ar', models.CharField(max_length=250, null=True)),
                ('full_name_ur', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=300)),
                ('shipping_address', models.TextField(max_length=400)),
                ('shipping_address_fa', models.TextField(max_length=400, null=True)),
                ('shipping_address_en', models.TextField(max_length=400, null=True)),
                ('shipping_address_ar', models.TextField(max_length=400, null=True)),
                ('shipping_address_ur', models.TextField(max_length=400, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_ordered', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('last_update', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده به پست'), ('delivered', 'تحویل داده شده')], default='pending', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آیتم های سفارش',
            },
        ),
        migrations.CreateModel(
            name='PaymentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(max_length=250)),
                ('shipping_full_name_fa', models.CharField(max_length=250, null=True)),
                ('shipping_full_name_en', models.CharField(max_length=250, null=True)),
                ('shipping_full_name_ar', models.CharField(max_length=250, null=True)),
                ('shipping_full_name_ur', models.CharField(max_length=250, null=True)),
                ('shipping_email', models.CharField(max_length=300)),
                ('shipping_phone', models.CharField(blank=True, max_length=25)),
                ('shipping_address1', models.CharField(blank=True, max_length=250)),
                ('shipping_address1_fa', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_address1_en', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_address1_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_address1_ur', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_address2', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_address2_fa', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_address2_en', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_address2_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_address2_ur', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=25)),
                ('shipping_city_fa', models.CharField(blank=True, max_length=25, null=True)),
                ('shipping_city_en', models.CharField(blank=True, max_length=25, null=True)),
                ('shipping_city_ar', models.CharField(blank=True, max_length=25, null=True)),
                ('shipping_city_ur', models.CharField(blank=True, max_length=25, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=25)),
                ('shipping_state_fa', models.CharField(blank=True, max_length=25, null=True)),
                ('shipping_state_en', models.CharField(blank=True, max_length=25, null=True)),
                ('shipping_state_ar', models.CharField(blank=True, max_length=25, null=True)),
                ('shipping_state_ur', models.CharField(blank=True, max_length=25, null=True)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=25)),
                ('shipping_country', models.CharField(blank=True, default='IRAN', max_length=25)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آدرس پرداخت',
                'verbose_name_plural': 'آدرس\u200cهای پرداخت',
            },
        ),
    ]
