# Generated by Django 5.2 on 2025-05-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymentaddress_options_alter_order_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending ', 'در انتظار پرداخت'), ('Processing ', 'در حال پردازش'), ('Shipped', 'ارسال شده به پست'), ('Delivered ', 'تحویل داده شده')], default='pending', max_length=50),
        ),
    ]
