# Generated by Django 5.2 on 2025-05-20 14:23

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_last_update_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_update',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
