# Generated by Django 5.2 on 2025-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_order_date_ordered_alter_order_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده به پست'), ('delivered', 'تحویل داده شده')], default='pending', max_length=50),
        ),
    ]
