# Generated by Django 5.2 on 2025-05-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='paymentaddress',
            options={'verbose_name': 'آدرس پرداخت', 'verbose_name_plural': 'آدرس\u200cهای پرداخت'},
        ),
        migrations.AddField(
            model_name='order',
            name='full_name_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name_fa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name_ur',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_ar',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_en',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_fa',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_ur',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_address1_ar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_address1_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_address1_fa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_address1_ur',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_address2_ar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_address2_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_address2_fa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_address2_ur',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_city_ar',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_city_en',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_city_fa',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_city_ur',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_full_name_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_full_name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_full_name_fa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_full_name_ur',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_state_ar',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_state_en',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_state_fa',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='shipping_state_ur',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
