# Generated by Django 5.2 on 2025-05-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_order_options_alter_paymentaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم های سفارش'},
        ),
    ]
