# Generated by Django 5.2 on 2025-05-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_product_picture'),
        ('cart', '0006_remove_cartitem_product_cartitem_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product'),
        ),
    ]
