# Generated by Django 6.0.7 on 2026-07-29 10:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionalproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام محصول')),
                ('name_fa', models.CharField(max_length=40, null=True, verbose_name='نام محصول')),
                ('name_en', models.CharField(max_length=40, null=True, verbose_name='نام محصول')),
                ('name_ar', models.CharField(max_length=40, null=True, verbose_name='نام محصول')),
                ('name_ur', models.CharField(max_length=40, null=True, verbose_name='نام محصول')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('description_fa', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('description_en', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('description_ar', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('description_ur', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('picture', models.ImageField(upload_to='upload/More_product')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت')),
                ('star', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('is_sale', models.BooleanField(default=False, verbose_name='قیمت تخفیف')),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت بعد از تخفیف')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات بیشتر',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته\u200cبندی')),
                ('name_fa', models.CharField(max_length=50, null=True, verbose_name='نام دسته\u200cبندی')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='نام دسته\u200cبندی')),
                ('name_ar', models.CharField(max_length=50, null=True, verbose_name='نام دسته\u200cبندی')),
                ('name_ur', models.CharField(max_length=50, null=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProductMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app1.additionalproduct')),
            ],
            options={
                'verbose_name': 'پیام محصول',
                'verbose_name_plural': 'پیام\u200cهای محصولات بیشتر',
            },
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.category', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام محصول')),
                ('name_fa', models.CharField(max_length=40, null=True, verbose_name='نام محصول')),
                ('name_en', models.CharField(max_length=40, null=True, verbose_name='نام محصول')),
                ('name_ar', models.CharField(max_length=40, null=True, verbose_name='نام محصول')),
                ('name_ur', models.CharField(max_length=40, null=True, verbose_name='نام محصول')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('description_fa', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('description_en', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('description_ar', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('description_ur', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='upload/product')),
                ('star', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('is_sale', models.BooleanField(default=False, verbose_name='تخفیف')),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت بعد از تخفیف')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app1.product')),
            ],
            options={
                'verbose_name': 'پیام محصول',
                'verbose_name_plural': 'پیام\u200cهای محصولات',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address1', models.CharField(blank=True, max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('zipcode', models.CharField(blank=True, max_length=25)),
                ('country', models.CharField(default='IRAN', max_length=25)),
                ('old_cart', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
