# Generated by Django 5.2 on 2025-04-24 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 7, 40, 50, 548541)),
        ),
    ]
