# Generated by Django 5.2 on 2025-04-28 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_additionalproduct_price_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 28, 6, 31, 55, 257779)),
        ),
    ]
