# Generated by Django 5.2 on 2025-04-29 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_additionalproduct_is_sale_additionalproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 29, 0, 23, 8, 289584)),
        ),
    ]
