# Generated by Django 5.2 on 2025-05-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_order_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
