# Generated by Django 5.2 on 2025-05-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_product_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
