# Generated by Django 5.2 on 2025-05-25 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_delete_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalproduct',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='additionalproductmessage',
            options={'verbose_name': 'پیام محصول اضافه', 'verbose_name_plural': 'پیام\u200cهای محصولات اضافه'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productmessage',
            options={'verbose_name': 'پیام محصول اضافه', 'verbose_name_plural': 'پیام\u200cهای محصولات اضافه'},
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='description_ar',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='description_fa',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='description_ur',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='name_ar',
            field=models.CharField(max_length=40, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='name_fa',
            field=models.CharField(max_length=40, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='name_ur',
            field=models.CharField(max_length=40, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=20, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=20, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ur',
            field=models.CharField(max_length=20, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ur',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=40, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=40, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ur',
            field=models.CharField(max_length=40, null=True, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='قیمت تخفیف'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت بعد از تخفیف'),
        ),
        migrations.AlterField(
            model_name='additionalproductmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='additionalproductmessage',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='additionalproductmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت بعد از تخفیف'),
        ),
        migrations.AlterField(
            model_name='productmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='productmessage',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='productmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
