# Generated by Django 5.2 on 2025-05-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_additionalproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalproduct',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات بیشتر'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی'},
        ),
    ]
